### PR TITLE
Development

### PR DESCRIPTION
**Pull request by rvvergara**
Weather App
- Utilized webpack's features to bundle the different modules 
- Utilized bootstrap css for styling
- Utilized fetch API for getting data from the Weather API
- Utilized 'pug-html-loader' for templating (breaking down the large html file into several partials for easier debugging and simpler coding)

How we subdivided our js files:
/src/js contains all the functionalities:
 - index.js is where we just call on the addEventListeners() function (which basically just adds event listeners to the search form and radio buttons to toggle between Celsius and Fahrenheit units)
- fetchData.js is where we do our data fetching from the API -> We return a promise that when resolved contains the data array of all the weather information we need (depending on the City searched for in the input box)
- domHelpers contains all the dom-relevant functions 
- elements.js contains all the constants and variables we need for the project

### CODE REVIEW

**Comment by talihomz** [comment]
## Great Weather App Implementation
---

This looks incredible!!! Great work guys!
dipto-weather

The code looks great too! Here are my thoughts:
1. `domHelpers.js`, `eventListeners.js` and `elements.js` should all probably be in one code file, since they have the same responsibility.(managing the DOM). It makes sense to split them since they are large, but this only makes understanding the functionality troublesome, since its just the same DOM manupilation split into 3 files.
2. [These two functions](https://github.com/rvvergara/javascript-weather-app/blob/bf675f1fc3f9def030ece1f6b513c0af225b1699/src/js/domHelpers.js#L73-L81) belong in their own code file, as they have nothing to do with DOM manupilation. (probably put them in `utils.js`)

Otherwise, everything else looks awesome, great job!

**Comment by rvvergara** [comment]
Thanks @talihomz ! Haha that's the shortest review we had and probably the easiest things to do (pun intended) :D We are so grateful for these.

**Comment by rvvergara** [comment]
> ## Great Weather App Implementation
> 
> This looks incredible!!! Great work guys!
> dipto-weather
> 
> The code looks great too! Here are my thoughts:
> 
>     1. `domHelpers.js`, `eventListeners.js` and `elements.js` should all probably be in one code file, since they have the same responsibility.(managing the DOM). It makes sense to split them since they are large, but this only makes understanding the functionality troublesome, since its just the same DOM manupilation split into 3 files.
> 
>     2. [These two functions](https://github.com/rvvergara/javascript-weather-app/blob/bf675f1fc3f9def030ece1f6b513c0af225b1699/src/js/domHelpers.js#L73-L81) belong in their own code file, as they have nothing to do with DOM manupilation. (probably put them in `utils.js`)
> 
> 
> Otherwise, everything else looks awesome, great job!

@talihomz , instead of placing all of those scripts into one big file, we decided to just create  a folder called 'domScripts' and house those 3 files. This way we still have separation and distinction of those dom scripts without bloating up a single file

**Comment by talihomz** [comment]
## Good Work on This
---
Code looks good now... 👍

**Comment by rvvergara** [comment]
> ## Good Work on This
> 
> Code looks good now... +1

Thanks! Merging it to Master now then..

**Pull request merged**
